config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

# get "pets", to: "pets#index", as:"pets"
# get "pets/new", to: "pets#new", as:"new_pets"
# post "pets", to: "pets#create"
# get "pets/:id/edit", to: "pets#edit", as:"edit_pet"
# get "pets/:id", to: "pets#show", as:"pet"
# patch "pets/:id/update", to: "pets#update"
# delete "pets/:id", to: "pets#destroy"
resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ["cat", "dog", "snake", "pig"]
  validates :name, presence: true
  validates :species,  inclusion: { in: SPECIES, message: "try again"}

  def found_days_ago
    return ( Date.today - found_on ).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pets_path
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path

  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for pet do |f| %>
  <%= f.input :name, placeholder: "Your name", hint:"other things" %>
  <%= f.input :address, label: "Address" %>
  <%= f.input :found_on, label: "Found_on" %>
  <%= f.input :species, collection: Pet::SPECIES, label: "Found_on" %>
  <%= f.button :submit, class: "btn btn-primary alert alert-danger" %>
<% end %>

app/views/pets/edit.html.erb
<div class="container">
  <h1>Edit Pet</h1>
  <%= render "form", pet: @pet %>
</div>

app/views/pets/index.html.erb
<h1>Pets</h1>
<%= link_to "Create", new_pet_path %>

<% @pets.each do |pet| %>
  <h2><%= pet.name %></h2>
  <p><%= pet.address %></p>
  <p>Lolote was found <%= pet.found_days_ago %> days ago</p>
  <%= link_to "Supprimer", pet_path(pet), method: :delete, data: { confirm: "Are you sure ?"} %>

  <%= link_to "Voir", pet_path(pet) %>
<% end %>
<h2></h2>

app/views/pets/new.html.erb
<div class="container">
  <h1>New Pet</h1>
  <%= render "form", pet: @pet %>
</div>

app/views/pets/show.html.erb
<h2><%= @pet.name %></h2>
<p><%= @pet.address %></p>
<p><%= @pet.species %></p>
<p>Lolote was found <%= @pet.found_days_ago %> days ago</p>
<%= link_to "Edit", edit_pet_path(@pet) %>
<%= link_to "< back", pets_path %>